ADAPTATION:
  METHOD: "TentMod"
  STEPS: 1
  LR: 0.01
  LAMBDA_ALIGNMENT: 0.01
  NUM_GENERATED_EXAMPLES: 256
  USE_PARAM_ALIGNMENT: False
  USE_EVAL_MODE: True
  OPTIM_MOMENTUM: 0.9
  PARAMS2ADAPT: 1-BN
MODEL:
  BACKBONE:
    BN_MOMENTUM: 0.0