ADAPTATION:
  METHOD: "TentMod"
  STEPS: 1
  LR: 0.01
  LAMBDA_ALIGNMENT: 3.0
  # LAMBDA_ALIGNMENT: 1000.0  # For param alignment
  NUM_GENERATED_EXAMPLES: 128
  OPTIM_MOMENTUM: 0.9
  PARAMS2ADAPT: 1-BN
MODEL:
  BACKBONE:
    BN_MOMENTUM: 0.0